CREATE USER IF NOT EXISTS 'flaskapp'@'%' IDENTIFIED BY 'flask123';

CREATE DATABASE IF NOT EXISTS testdb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES
ON testdb.* TO 'flaskapp'@'%';

FLUSH PRIVILEGES;

USE testdb;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO messages (message) VALUES ('Hello from MySQL in Docker!');
