apiVersion: v1
data:
  DB_APP_PASSWORD: Zmxhc2stMTIzQDQ1
  DB_APP_USER: Zmxhc2thcHA=
  DB_NAME: dGVzdGRi
  DB_ROOT_PASSWORD: Zmxhc2stMTIzQDQ1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-mysql
