apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
  namespace: flask-mysql
spec:
  ports: 
  - port: 3306
  clusterIP: None
  selector:
    app: mysql-replica-stateful
    role: replica

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysql-replica
  namespace: flask-mysql
spec:
  replicas: 2
  serviceName: mysql-replica
  selector:
    matchLabels:
      app: mysql-replica-stateful
      role: replica
  template:
    metadata:
      labels: 
        app: mysql-replica-stateful  
        role: replica
    spec:
      containers:
        - name: mysql
          image: bitnamilegacy/mysql:8.0.39-debian-12-r0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_MODE
              value: "slave"
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_USER
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_REPLICATION_PASSWORD
            - name: MYSQL_MASTER_HOST
              value: "mysql-primary.flask-mysql.svc.cluster.local" 
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /bitnami/mysql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi