apiVersion: v1
data:
  MYSQL_DATABASE: dGVzdGRi
  MYSQL_PASSWORD: Zmxhc2sxMjM=
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==
  MYSQL_USER: Zmxhc2thcHA=

  MYSQL_REPLICATION_USER: bWFzdGVyX3VzZXI=
  MYSQL_REPLICATION_PASSWORD: bWFzdGVyX3Bhc3M=

  EXPORTER_USER: ZXhwb3J0ZXI=
  EXPORTER_PASSWORD: ZXhwb3J0ZXIxMjM=
  EXPORTER_DSN: ZXhwb3J0ZXI6ZXhwb3J0ZXIxMjNAKG15c3FsLXByaW1hcnkuZmxhc2stbXlzcWwuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNikv


kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-mysql